#!/usr/bin/env python3
"""
Phase 4: Daily Digest Generator
News Intelligence System

生成每日摘要：詳細 MD + 簡報
"""

import os
import json
from datetime import datetime
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent.parent
CACHE_DIR = SCRIPT_DIR / "cache"
OUTPUT_DIR = SCRIPT_DIR / "output"
WIKI_NEWS_DIR = Path("~/.openclaw/workspace/wiki/AI-News/daily").expanduser()

def load_scored_items():
    """載入已評分的新聞"""
    scored_file = CACHE_DIR / "scored_items.json"
    if scored_file.exists():
        with open(scored_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get('items', [])
    return []

def generate_headlines(items: list) -> str:
    """生成頭條板塊"""
    headlines = [i for i in items if i['level'] == '🔥 HEADLINE']
    important = [i for i in items if i['level'] == '⭐ IMPORTANT']
    notable = [i for i in items if i['level'] == '📌 NOTABLE']
    
    lines = ["## 🔥 今日行業大事\n"]
    
    # Top headlines
    if headlines:
        for item in headlines[:5]:
            score = item['score']
            source = item['source']
            title = item['title']
            link = item.get('link', '')
            summary = item.get('summary', '')[:200]
            
            lines.append(f"### {title}\n")
            lines.append(f"- **Source:** {source} | **Score:** {score}分\n")
            if link:
                lines.append(f"- **Link:** {link}\n")
            if summary:
                lines.append(f"- **摘要:** {summary}...\n")
            lines.append("\n")
    
    return "".join(lines)

def generate_for_you(items: list) -> str:
    """生成"對期哥有用"板塊"""
    important = [i for i in items if i['level'] in ['🔥 HEADLINE', '⭐ IMPORTANT']]
    
    lines = ["## 💡 對你有用\n"]
    
    if important:
        for item in important[:5]:
            title = item['title']
            source = item['source']
            summary = item.get('summary', '')[:150]
            score_breakdown = item.get('score_breakdown', {})
            
            lines.append(f"### {title}\n")
            lines.append(f"- **Source:** {source} | **Score:** {item['score']}分\n")
            if score_breakdown:
                cats = list(score_breakdown.keys())
                lines.append(f"- **分類:** {', '.join(cats)}\n")
            if summary:
                lines.append(f"- **摘要:** {summary}...\n")
            lines.append("\n")
    else:
        lines.append("今日暫無特別相關的新聞。\n")
    
    return "".join(lines)

def generate_notable(items: list) -> str:
    """生成"值得關注"板塊"""
    notable = [i for i in items if i['level'] in ['📌 NOTABLE', '⭐ IMPORTANT']]
    notable = [i for i in notable if i['level'] != '🔥 HEADLINE']
    
    lines = ["## 📌 值得關注\n"]
    
    if notable:
        for item in notable[:5]:
            title = item['title']
            source = item['source']
            score = item['score']
            
            lines.append(f"- [{source}] {title} ({score}分)\n")
    else:
        lines.append("今日暫無值得特別關注的新聞。\n")
    
    return "".join(lines)

def generate_key_signals(items: list) -> str:
    """生成"關鍵信號"板塊"""
    lines = ["## 🔑 今日關鍵信號\n"]
    
    # Count by source
    source_counts = {}
    for item in items:
        source = item['source']
        source_counts[source] = source_counts.get(source, 0) + 1
    
    lines.append("### 新聞來源分佈\n")
    for source, count in sorted(source_counts.items(), key=lambda x: -x[1])[:5]:
        lines.append(f"- **{source}:** {count} 條\n")
    
    # Score distribution
    lines.append("\n### 分數分佈\n")
    levels_count = {
        '🔥 HEADLINE': 0,
        '⭐ IMPORTANT': 0,
        '📌 NOTABLE': 0,
        '📝 GENERAL': 0
    }
    for item in items:
        levels_count[item['level']] = levels_count.get(item['level'], 0) + 1
    
    for level, count in levels_count.items():
        if count > 0:
            lines.append(f"- **{level}:** {count}\n")
    
    return "".join(lines)

def generate_markdown(items: list, date_str: str) -> str:
    """生成完整 Markdown 文件"""
    md = f"""# AI News Digest - {date_str}

> 🤖 News Intelligence System 生成 | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 📊 數據概覽

| 指標 | 數值 |
|------|------|
| **總新聞數** | {len(items)} |
| **頭條** | {len([i for i in items if i['level'] == '🔥 HEADLINE'])} |
| **重要** | {len([i for i in items if i['level'] == '⭐ IMPORTANT'])} |
| **值得關注** | {len([i for i in items if i['level'] == '📌 NOTABLE'])} |

---

"""
    
    md += generate_headlines(items)
    md += "\n---\n"
    md += generate_for_you(items)
    md += "\n---\n"
    md += generate_notable(items)
    md += "\n---\n"
    md += generate_key_signals(items)
    
    md += f"""

---

_🤖 Generated by News Intelligence System | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_
"""
    
    return md

def generate_brief_summary(items: list) -> str:
    """生成簡報（用於 Telegram）"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    
    lines = [f"📰 AI News Digest - {date_str}\n"]
    lines.append("=" * 40 + "\n\n")
    
    # Top headlines
    headlines = [i for i in items if i['level'] == '🔥 HEADLINE'][:3]
    important = [i for i in items if i['level'] == '⭐ IMPORTANT'][:3]
    
    if headlines:
        lines.append("🔥 頭條\n")
        for i, item in enumerate(headlines, 1):
            title = item['title'][:60]
            lines.append(f"{i}. {title}...\n")
        lines.append("\n")
    
    if important:
        lines.append("⭐ 重要\n")
        for i, item in enumerate(important, 1):
            title = item['title'][:60]
            lines.append(f"{i}. {title}...\n")
        lines.append("\n")
    
    # Stats
    total = len(items)
    lines.append(f"_📊 共 {total} 條新聞 | 🤖 News Intelligence System_")
    
    return "".join(lines)

def save_to_wiki(md: str, date_str: str):
    """保存到 Wiki"""
    WIKI_NEWS_DIR.mkdir(parents=True, exist_ok=True)
    wiki_file = WIKI_NEWS_DIR / f"{date_str}.md"
    
    with open(wiki_file, 'w', encoding='utf-8') as f:
        f.write(md)
    
    return wiki_file

def save_to_output(md: str, date_str: str):
    """保存到 output 目錄"""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_file = OUTPUT_DIR / "daily" / f"{date_str}.md"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(md)
    
    return output_file

def main():
    """主函數"""
    print(f"📋 Daily Digest Generator - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)
    
    items = load_scored_items()
    
    if not items:
        print("❌ No scored items found. Run scorer.py first.")
        return
    
    print(f"📥 Loaded {len(items)} scored items")
    
    date_str = datetime.now().strftime('%Y-%m-%d')
    
    # Generate detailed MD
    md = generate_markdown(items, date_str)
    
    # Save to wiki
    wiki_file = save_to_wiki(md, date_str)
    print(f"✅ Saved to wiki: {wiki_file}")
    
    # Save to output
    output_file = save_to_output(md, date_str)
    print(f"✅ Saved to output: {output_file}")
    
    # Generate brief summary for Telegram
    brief = generate_brief_summary(items)
    print(f"\n📱 Brief Summary (Telegram):")
    print("-" * 40)
    print(brief)
    
    # Save brief separately for Telegram use
    brief_file = OUTPUT_DIR / f"brief_{date_str}.txt"
    with open(brief_file, 'w', encoding='utf-8') as f:
        f.write(brief)
    print(f"\n✅ Brief saved to: {brief_file}")

if __name__ == "__main__":
    main()
